pipeline{
    agent{
        label 'qa'
    }
    
        stages{
            stage('Build details'){
                steps{
                    sh '''
                    echo '"SYSTEM DETAILS"'
                    uname -a
                    '''
                }
            }
            stage('Build-Memory'){
                steps{
                    sh '''
                    echo "MEMORY DETAILS"
                    free
                    '''
                }
            }
            stage('Build-CPU details'){
                steps{
                    sh '''
                    echo "CPU DETAILS"
                    lscpu
                    '''
                }
            }
            stage('Build-Disk details'){
                steps{
                    sh '''
                    echo "TODAYS DATE"
                    date
                    '''
                }
            }
                 stage('Build-Process command'){
                steps{
                    sh '''
                    echo "Process command"
                    ps -ef
                    '''
                }
            }
 
        }
}