pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo "building"
            }
        }
        stage('Test'){
            steps{
                echo "Testing"
            }
        }
        stage('Deploy'){
            steps{
                echo "deploying"
                sh '''
                    echo "hello"
                    ls -l
                '''
            }
        }
    }
}
